<div class="row">
  <div class="col-md-12"><h2 align="center">SCORECARD</h2></div>
  <div align="center" class="col-md-12">
    <a href="agregar">
      <button type="button" class="btn btn-primary add">
        <span class="glyphicon glyphicon-plus"></span> Agregar Score
      </button>
    </a>
    <a href="<?php echo APP_URL;?>/drivers/index">
      <button type="button" class="btn btn-primary add">
        <span class="glyphicon glyphicon-asterisk"></span> Drivers
      </button>
    </a>
  </div>
</div>
 
<br>
<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-tabs">

       <?php
        $i = 0;
        $driverId=array();
      foreach ($drivers as $driver): 
        if ($i==0): ?>
          <li class="active"><a data-toggle="tab" href="#<?php echo $driver["drivers"]["id"]; ?>"><?php echo $driver["drivers"]["nombre"]; ?></a></li>
        <?php else: ?>
         <li><a data-toggle="tab" href="#<?php echo $driver["drivers"]["id"]; ?>"><?php echo $driver["drivers"]["nombre"]; ?></a></li>
        <?php 
        endif; 
        $i++;
        $driverId["id"][] = $driver["drivers"]["id"];
        $driverId["nombre"][] = $driver["drivers"]["nombre"];
      endforeach;?>
    </ul>
  </div>
</div>
<div class="tab-content">
<?php
  for ($j=0; $j < $i ; $j++):
    if ($j==0): ?>
      <div id="<?php echo $driverId["id"][$j]; ?>" class="tab-pane fade in active">
    <?php else: ?>
      <div id="<?php echo $driverId["id"][$j]; ?>" class="tab-pane fade ">
    <?php endif; 

  $suma=array();
  $x=0;
  ?>
    <br>
<?php
    foreach ($scores as $score) {
      $registros[$score["scores"]["stats_id"]]["valor"][$score["periodos"]["id"]] = $score["scores"]["valor"];
      $registros[$score["scores"]["stats_id"]]["id"][$score["periodos"]["id"]] = $score["scores"]["id"];
    }
?>    
<table class="table table-bordered">
<tr>
  <th></th>
  <?php
   foreach ($periodos as $periodo) {
    echo "<th>".$periodo["periodos"]["nombre"]."</th>";
   }
   ?>

</tr>
  <tr>
    
<?php
for ($j=1; $j <= 4 ; $j++) {
  echo "<td>".$stats[$j-1]["stats"]["nombre"]."</td>";

  for ($i=1; $i <= 4 ; $i++) { 
    if (!empty($registros[$j]["valor"][$i])) {
      echo "<td>".
      $this->Html->link(
                      $registros[$j]["valor"][$i],
                      array(
                          "controller"=>"scores",
                          "method"=>"editar",
                          "args"=>$registros[$j]["id"][$i]
                          ),
                      array(
                          "title"=>"Editar score"     
                          )
             ).
      "</td>";
    }else{
      echo "<td></td>";
    }
//    @$suma[$x++]+= $registros[$j]["valor"][$i];
  }
  echo "</tr>";

}

?>
  
<tr>
          <th><p color="red">Promedios</p></th>
          
            <?
            $sumaprom=0;
             foreach ($suma as $total) {
               echo "<td>".$total/4 ."</td>";
                
                $sumaprom+=$total/4;
             }
            ?>
        </tr>
    </table>
    
    <br>
    <h1 align="center"><?php echo "Promedio Total del mes: ". $sumaprom/4; ?></h1>
  </div>
<?php endfor; ?>
</div>