<div class="row">
  <div class="col-sm-4"><h2>Agregar Driver</h2></div>
  <div class="col-sm-4"></div>
  <div class="col-sm-4"><br /><a href="index"><button type="button" class="btn btn-primary add"><span class="glyphicon glyphicon-arrow-left"></span> Volver a Drivers</button></a></div>
</div>

<form action="<?php echo APP_URL; ?>/drivers/agregar" method="POST" role="form">
	<div class="form-group">
    	<label for="nombre">Nombre:</label>
    	<input type="text" class="form-control" id="nombre" name="nombre">
 	</div>
	<button type="submit" class="btn btn-default">Guardar driver</button>
</form>