
<div class="row">
  <div class="col-sm-4"><h2>Editar driver</h2></div>
  <div class="col-sm-4"></div>
  <div class="col-sm-4"><br /><a href="<?php echo APP_URL; ?>/drivers/index"><button type="button" class="btn btn-primary add"><span class="glyphicon glyphicon-arrow-left"></span> Volver a drivers</button></a></div>
</div>

<form action="<?php echo APP_URL; ?>/drivers/editar" method="POST" role="form">
	<input type="hidden" name="id" value="<?php echo $driver["id"]; ?>">
	<div class="form-group">
    	<label for="nombre">Nombre:</label>
    	<input type="text" class="form-control" id="nombre" name="nombre" value="<?php echo $driver["nombre"]; ?>">
 	</div>
	<button type="submit" class="btn btn-default">Guardar driver</button>
</form>