-- MySQL Script generated by MySQL Workbench
-- Wed Feb 21 13:48:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scoreboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scoreboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scoreboard` DEFAULT CHARACTER SET utf8 ;
USE `scoreboard` ;

-- -----------------------------------------------------
-- Table `scoreboard`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoreboard`.`drivers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scoreboard`.`stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoreboard`.`stats` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scoreboard`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoreboard`.`periodos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scoreboard`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoreboard`.`scores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `drivers_id` INT UNSIGNED NOT NULL,
  `stats_id` INT UNSIGNED NOT NULL,
  `periodos_id` INT UNSIGNED NOT NULL,
  `valor` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`, `drivers_id`, `stats_id`, `periodos_id`),
  INDEX `fk_socres_drivers_idx` (`drivers_id` ASC),
  INDEX `fk_socres_stats1_idx` (`stats_id` ASC),
  INDEX `fk_scores_periodos1_idx` (`periodos_id` ASC),
  CONSTRAINT `fk_socres_drivers`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `scoreboard`.`drivers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socres_stats1`
    FOREIGN KEY (`stats_id`)
    REFERENCES `scoreboard`.`stats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scores_periodos1`
    FOREIGN KEY (`periodos_id`)
    REFERENCES `scoreboard`.`periodos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
